jenkins-x/jx3-pipeline-catalog

packs/appserver/.lighthouse/jenkins-x/pullrequest.yaml, packs/appserver/.lighthouse/jenkins-x/release.yaml, packs/cwp/.lighthouse/jenkins-x/pullrequest.yaml, packs/docker-helm/.lighthouse/jenkins-x/pullrequest.yaml, packs/docker-helm/.lighthouse/jenkins-x/release.yaml, packs/docker/.lighthouse/jenkins-x/pullrequest.yaml, packs/docker/.lighthouse/jenkins-x/release.yaml, packs/gradle/.lighthouse/jenkins-x/pullrequest.yaml, packs/jenkins/.lighthouse/jenkins-x/pullrequest.yaml, packs/jenkins/.lighthouse/jenkins-x/release.yaml
to avoid copy paste month steps
=> chore: polish the use of _JAVA_OPTIONS

packs/javascript/Dockerfile, packs/typescript/Dockerfile
Signed-off-by: Hervé Le Meur <herve.lemeur@sixense-group.com>
=> fix: upgrade to nodejs 12

packs/go-plugin-multiarch/.lighthouse/jenkins-x/pullrequest.yaml, packs/go-plugin-multiarch/.lighthouse/jenkins-x/release.yaml, packs/go-plugin-multiarch/.lighthouse/jenkins-x/triggers.yaml
and add a multiarch pack for plugins which also make a multi-arch image
=> fix: use updatebot in plugins

README.md
from blog article, https://jenkins-x.io/blog/2020/11/11/accelerate-tekton/#custom-pipeline-catalogs
added an example
=> feat(doc): add custom pipeline catalog section

packs/gradle/charts/Makefile, packs/javascript-ui-nginx/charts/Makefile, packs/javascript/charts/Makefile, packs/maven-java11/charts/Makefile, packs/maven-node-ruby/charts/Makefile, packs/maven-quarkus/charts/Makefile, packs/maven/charts/Makefile, packs/ml-python-gpu-service/charts/Makefile, packs/ml-python-gpu-training/charts/Makefile, packs/ml-python-service/charts/Makefile, packs/ml-python-training/charts/Makefile, packs/php/charts/Makefile, packs/python/charts/Makefile, packs/ruby/charts/Makefile, packs/rust/charts/Makefile
Sorry, missed these in my previous pr.
=> fix(git): add missing 'chore' for conventional commits

packs/go-plugin-multiarch/.lighthouse/jenkins-x/release.yaml, packs/go-plugin/.lighthouse/jenkins-x/release.yaml
=> fix: use better image for helm releases

packs/C++/.lighthouse/jenkins-x/release.yaml, packs/D/.lighthouse/jenkins-x/release.yaml, packs/apps/.lighthouse/jenkins-x/release.yaml, packs/appserver/.lighthouse/jenkins-x/release.yaml, packs/csharp/.lighthouse/jenkins-x/release.yaml, packs/cwp/.lighthouse/jenkins-x/release.yaml, packs/docker-helm/.lighthouse/jenkins-x/release.yaml, packs/go-mongodb/.lighthouse/jenkins-x/release.yaml, packs/go/.lighthouse/jenkins-x/release.yaml, packs/gradle/.lighthouse/jenkins-x/release.yaml, packs/helm/.lighthouse/jenkins-x/release.yaml, packs/javascript-ui-nginx/.lighthouse/jenkins-x/release.yaml, packs/javascript/.lighthouse/jenkins-x/release.yaml, packs/maven-java11/.lighthouse/jenkins-x/release.yaml, packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml, packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml, packs/maven/.lighthouse/jenkins-x/release.yaml, packs/ml-python-gpu-service/.lighthouse/jenkins-x/release.yaml, packs/ml-python-service/.lighthouse/jenkins-x/release.yaml, packs/php/.lighthouse/jenkins-x/release.yaml, packs/python/.lighthouse/jenkins-x/release.yaml, packs/ruby/.lighthouse/jenkins-x/release.yaml, packs/rust/.lighthouse/jenkins-x/release.yaml, packs/scala/.lighthouse/jenkins-x/release.yaml, packs/typescript/.lighthouse/jenkins-x/release.yaml
so we generate PRs for Production too
=> fix: switch to --all mode for promote

tasks/rust/pullrequest.yaml, tasks/rust/release.yaml
rebased https://github.com/jenkins-x/jx3-pipeline-catalog/pull/253
thanks @HarryGogonis
=> fix: add path flag to build-cargo-install

tasks/rust/pullrequest.yaml, tasks/rust/release.yaml
=> chore: avoid alpine image for now

packs/C++/preview/values.yaml.gotmpl, packs/D/preview/values.yaml.gotmpl, packs/appserver/preview/values.yaml.gotmpl, packs/csharp/preview/values.yaml.gotmpl, packs/cwp/preview/values.yaml.gotmpl, packs/go-mongodb/preview/values.yaml.gotmpl, packs/go/preview/values.yaml.gotmpl, packs/gradle/preview/values.yaml.gotmpl, packs/javascript-ui-nginx/preview/values.yaml.gotmpl, packs/javascript/preview/values.yaml.gotmpl, packs/maven-java11/preview/values.yaml.gotmpl, packs/maven-node-ruby/preview/values.yaml.gotmpl, packs/maven-quarkus/preview/values.yaml.gotmpl, packs/maven/preview/values.yaml.gotmpl, packs/ml-python-gpu-service/preview/values.yaml.gotmpl, packs/ml-python-gpu-training/preview/values.yaml.gotmpl, packs/ml-python-service/preview/values.yaml.gotmpl, packs/ml-python-training/preview/values.yaml.gotmpl, packs/php/preview/values.yaml.gotmpl, packs/python/preview/values.yaml.gotmpl, packs/ruby/preview/values.yaml.gotmpl, packs/rust/preview/values.yaml.gotmpl, packs/scala/preview/values.yaml.gotmpl, packs/typescript/preview/values.yaml.gotmpl
Fixes https://github.com/jenkins-x/jx3-gitops-template/issues/17
=> fix: use 'Always' as imagePullPolicy to avoid using old images if the PR build count is reseted

tasks/cwp/release.yaml, tasks/maven-java11/pullrequest.yaml, tasks/maven-node-ruby/pullrequest.yaml, tasks/maven-quarkus/pullrequest.yaml, tasks/maven/pullrequest.yaml, tasks/scala/pullrequest.yaml, tasks/scala/release.yaml
so that we reuse the same nexus mirror
=> chore: add maven settings for PRs too

helm/charts/templates/ingress.yaml
combining defaults from the requirements to the local chart values
=> fix: add more sophisticated logic for combining ingress annotations

tasks/maven-java11/pullrequest.yaml, tasks/maven-node-ruby/pullrequest.yaml, tasks/maven/pullrequest.yaml
to try remove flakiness in the BDD tests
=> fix: use consistent commands for maven PRs

packs/appserver/.lighthouse/jenkins-x/pullrequest.yaml, packs/appserver/.lighthouse/jenkins-x/release.yaml, packs/cwp/.lighthouse/jenkins-x/pullrequest.yaml, packs/jenkins/.lighthouse/jenkins-x/pullrequest.yaml, packs/jenkins/.lighthouse/jenkins-x/release.yaml, packs/maven-java11/.lighthouse/jenkins-x/pullrequest.yaml, packs/maven-java11/.lighthouse/jenkins-x/release.yaml, packs/maven-node-ruby/.lighthouse/jenkins-x/pullrequest.yaml, packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml, packs/maven-quarkus/.lighthouse/jenkins-x/pullrequest.yaml, packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml, packs/maven/.lighthouse/jenkins-x/pullrequest.yaml, packs/maven/.lighthouse/jenkins-x/release.yaml, tasks/appserver/pullrequest.yaml, tasks/appserver/release.yaml, tasks/cwp/pullrequest.yaml, tasks/cwp/release.yaml, tasks/jenkins/pullrequest.yaml, tasks/jenkins/release.yaml, tasks/maven-java11/pullrequest.yaml, tasks/maven-java11/release.yaml, tasks/maven-node-ruby/pullrequest.yaml, tasks/maven-node-ruby/release.yaml, tasks/maven-quarkus/pullrequest.yaml, tasks/maven-quarkus/release.yaml, tasks/maven/pullrequest.yaml, tasks/maven/release.yaml, tasks/scala/pullrequest.yaml, tasks/scala/release.yaml
as we sometimes get failures to download spring boot pom.xml from preview pipelines (even though nexus has the pom.xml)
=> fix: for flaky maven downloads in BDD tests

environment/.lighthouse/jenkins-x/pullrequest.yaml, environment/.lighthouse/jenkins-x/release.yaml
so that they use the shiny uses: syntax
=> fix: upgrade environment pipelines

tasks/C++/release.yaml, tasks/D/release.yaml, tasks/appserver/release.yaml, tasks/csharp/release.yaml, tasks/cwp/release.yaml, tasks/docker-helm/release.yaml, tasks/docker/release.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/release.yaml, tasks/go/release.yaml, tasks/gradle/release.yaml, tasks/helm/release.yaml, tasks/javascript-ui-nginx/release.yaml, tasks/javascript/release.yaml, tasks/jenkins/release.yaml, tasks/maven-java11/release.yaml, tasks/maven-node-ruby/release.yaml, tasks/maven-quarkus/release.yaml, tasks/maven/release.yaml, tasks/ml-python-gpu-service/release.yaml, tasks/ml-python-service/release.yaml, tasks/php/release.yaml, tasks/python/release.yaml, tasks/ruby/release.yaml, tasks/rust/release.yaml, tasks/scala/release.yaml, tasks/typescript/release.yaml
so we can more easily modify yaml files at specific paths without unnecessary yaml changes
=> fix: upgrade to nicer yset command

packs/ml-python-gpu-service/charts/values.yaml, packs/ml-python-gpu-training/charts/values.yaml, packs/ml-python-service/charts/values.yaml, packs/ml-python-training/charts/values.yaml, tasks/ml-python-training/release.yaml
Signed-off-by: Terry Cox <terry@bootstrap.je>
=> fix: Set defaults for MLOps

packs/ml-python-service/.lighthouse/jenkins-x/release.yaml
Signed-off-by: Terry Cox <terry@bootstrap.je>
=> fix: Realign step name with task definition

tasks/git-clone/git-clone-pr.yaml, tasks/git-clone/git-clone.yaml
=> fix: add optional env vars for git cloning

packs/ml-python-gpu-training/.lighthouse/jenkins-x/pullrequest.yaml, packs/ml-python-gpu-training/.lighthouse/jenkins-x/release.yaml, packs/ml-python-gpu-training/.lighthouse/jenkins-x/triggers.yaml, tasks/ml-python-gpu-training/pullrequest.yaml, tasks/ml-python-gpu-training/release.yaml
Signed-off-by: Terry Cox <terry@bootstrap.je>
=> feat: Add GPU support

tasks/ml-python-gpu-training/release.yaml
Signed-off-by: Terry Cox <terry@bootstrap.je>
=> fix: Limits must be set for GPU utilisation

environment/.lighthouse/jenkins-x/pullrequest.yaml
as it seems to break installs/regen
=> chore: revert the custom merge strategy for now

tasks/git-clone/git-clone-pr.yaml
=> fix: remove redundant variable command from git clone pr task

tasks/go-plugin-multiarch/pullrequest.yaml
=> refactor: add pipeline lint step to go plugin multiarch task

tasks/go-plugin/release.yaml
Source: https://goreleaser.com/cmd/goreleaser_release/
=> fix: set goreleaser release timeout to 1h

tasks/go-cli/release.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/release.yaml
=> chore: upgrade goreleaser to 1.8.3

tasks/go-plugin/pullrequest.yaml, tasks/go/pullrequest.yaml
=> chore: increase timeout for golangci lint to 30m

tasks/go-cli/pullrequest.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
=> refactor: upgrade go to 1.17.11

tasks/go-cli/pullrequest.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
=> refactor: upgrade go version to 1.18.4

tasks/go-plugin/release.yaml, tasks/supply-chain-security/task.yaml
=> feat: add tasks for supply chain security

tasks/supply-chain-security/task.yaml
=> fiix: edit the indent for task

tasks/supply-chain-security/task.yaml
=> fix: edit env reference in the catalog

tasks/supply-chain-security/task.yaml
=> fix: add syft binary location to PATH

tasks/go-plugin/release.yaml, tasks/supply-chain-security/task.yaml
=> fix: add syft install location to PATH

tasks/supply-chain-security/task.yaml
=> fix: use sh instead of bash for oras step

tasks/supply-chain-security/task.yaml
=> feat: add grype tasks

tasks/supply-chain-security/task.yaml
=> feat: add cleanup image.tar after generating sbom

tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go/pullrequest.yaml
=> chore: upgrade golang ci lint to 1.47.3 to support go 1.18

tasks/go-plugin/release.yaml
=> fix: edit goversion env

tasks/flutter/release.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/release.yaml, tasks/terraform/release.yaml, tasks/updatebot/release.yaml
=> chore: manually bump jx updatebot to 0.3.6

tasks/go-cli/pullrequest.yaml, tasks/go-cli/release.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
- switch to custom goreleaser image
- update golangci-lint to 1.50.0
- switch to alpine for go build and test steps
=> refactor: upgrade go version to 1.19.2

tasks/go-cli/pullrequest.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
=> revert: go back to go non-alpine image

tasks/go-cli/pullrequest.yaml, tasks/go-cli/release.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
This PR updates go from `1.19.2` to `1.19.3`
=> refactor: update go:1.19.3

tasks/go-plugin/pullrequest.yaml, tasks/go/pullrequest.yaml
=> fixe: remove non existing paameter --deadline

packs/javascript-yarn/Dockerfile, packs/javascript/Dockerfile, packs/typescript/Dockerfile, tasks/javascript-ui-nginx/pullrequest.yaml, tasks/javascript-ui-nginx/release.yaml, tasks/javascript-yarn/release.yaml, tasks/javascript/pullrequest.yaml, tasks/javascript/release.yaml, tasks/lookml/lint.yaml, tasks/typescript/pullrequest.yaml, tasks/typescript/release.yaml
Running into issues with building node applications as node version is outdated.
Updated `node-slim` to latest version.
=> chore: update node-slim 14 -> 20

tasks/go-cli/pullrequest.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
=> chore:  upgrade to go 1.23.2

tasks/go-cli/pullrequest.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
=> fix: alpine doesn't suffice for go pipelines
