.gitignore, packs/nop/.lighthouse/jenkins-x/pullrequest.yaml
This PR fixes the nop pack's PipelineRun yaml by declaring "workspace-volume" in the volumes section (so that the volume can be mounted into tasks).
=> fix: add missing volume to nop pack

environment/.lighthouse/jenkins-x/release.yaml
so we don't trigger a PR pipeline on releases
=> fix: use correct pipeline for releases

packs/go-plugin-multiarch/.lighthouse/jenkins-x/release.yaml, packs/go-plugin/.lighthouse/jenkins-x/release.yaml
we can't use `sh` in the `golang` image, otherwise the `source .jx/variables.sh` cmd won't work:
```
Showing logs for build jenkins-x/jx-pipelines-visualizer/head #7 stage chart and container step-release-binary
/tekton/scripts/script-4-zd49r: 2: /tekton/scripts/script-4-zd49r: source: not found
```
switching to `bash` fixes the issue
=> fix: go build with jx variables

helm/preview/helmfile.yaml
to ensure we eagerly delete preview pods which have not yet had their workload identity repicated
=> fix: add a verify pod chart

tasks/maven-java11/pullrequest.yaml, tasks/maven-node-ruby/pullrequest.yaml, tasks/maven-quarkus/pullrequest.yaml
we should not modify the maven pom.xml on PR pipelines as we need to keep the SNAPSHOT version
=> chore: do not change version for PRs

helm/charts/templates/deployment.yaml
This is needed by Prometheus to scrape the pods of a deployment.
This simplifies the configuration of a ServiceMonitor when using Prometheus: 
For example: 
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: fmtok8s-servicemonitor 
labels:
release: myprometheus
spec:
selector:
matchLabels:
draft: draft-app
namespaceSelector:
matchNames:
- default
jobLabel: service-stats
endpoints:
- path: /actuator/prometheus
**targetPort: http**
interval: 15s
```
Where the target port is the name added in this PR.
=> Adding default name to container port inside a Deployment

packs/php/charts/values.yaml
Fixes https://github.com/jenkins-x/jx3-pipeline-catalog/issues/460
=> fix: use 80 as internal port for th PHP buildpack

environment/.lighthouse/jenkins-x/triggers.yaml
So we can easily distinguish app release jobs/pods from the env release jobs/pods.
=> chore: add a prefix to the env release pipeline name

README.md
Based on what I find in my extensions directory after using the catalog I believe that the path should be `extensions/pipeline-catalog.yaml` instead of `extensions/pipelines-catalog.yaml`
=> fix: Fix `extensions/pipeline-catalog.yaml` filename in `README.md`

tasks/git-clone/git-clone-pr.yaml, tasks/git-clone/git-clone.yaml
When you checkout a SHA as it's done here, git goes into detached head mode and loses all the nice metadata related to the branch. Ran into an issue with this when running code coverage tooling which would upload its results and tag it using git metadata.
This achieves the exact same purpose of checking out a particular SHA (note that the clone is hard-reset to the SHA on L30, but within the context of the checked out branch), and maintains the same printing, but is a little cleaner.
=> Maintain branch name semantics in git clone

tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/release.yaml
see https://github.com/jenkins-x/issues/issues/44
let's publish our container images with a `latest` tag by default, so that we can reference it from the master/main branches of our git repos (instead of referencing an old tag/version)
=> chore(go-plugin): publish latest tag for container image

packs/lookml/.lighthouse/README.md, packs/lookml/.lighthouse/jenkins-x/lint.yaml, packs/lookml/.lighthouse/jenkins-x/pullrequest.yaml, packs/lookml/.lighthouse/jenkins-x/release.yaml, packs/lookml/.lighthouse/jenkins-x/triggers.yaml, packs/lookml/charts/.helmignore, packs/lookml/charts/Chart.yaml, packs/lookml/charts/Kptfile, packs/lookml/charts/Makefile, packs/lookml/charts/README.md, packs/lookml/charts/templates/NOTES.txt, packs/lookml/charts/templates/_helpers.tpl, packs/lookml/charts/templates/deploy-hook-job.yaml, packs/lookml/charts/values.yaml, tasks/lookml/lint.yaml, tasks/lookml/pullrequest.yaml, tasks/lookml/release.yaml
- linting using [look at me sideways](https://github.com/looker-open-source/look-at-me-sideways)
- data tests and sql validation tests using [spectacles CI](https://github.com/spectacles-ci/spectacles). README.md contains instructions on setting up required api credentials
- release pipeline ships a helm chart which curls an arbitrary looker endpoint
typically, you don't bake a docker image containing lookml code. it's synced straight from git to the looker instance. the included chart defaults to using curl to hit the looker instance deploy endpoint, but can be customized to include a docker image that runs looker api commands, etc
=> feat: create lookml pack and pipelines

tasks/git-clone/git-clone-env-pr.yaml
in my multicluster setup, i frequently get merge conflicts in my automated production promotion cluster PRs. these are usually related to `jx-verify` config-root files. `jx gitops upgrade`-ing my cluster hasn't helped. i also occasionally get similar conflicts in my dev/staging cluster.
related slack thread: https://kubernetes.slack.com/archives/C9MBGQJRH/p1625017001157400
the changes in this pr would drop the previous commit if `jx gitops git merge --rebase --merge-arg "-Xtheirs"` fails and if the commit title contains the string 'regenerate'.
=> fix: drop up to 2 'regenerate' commits on merge conflict

tasks/go-plugin/pullrequest.yaml, tasks/go/pullrequest.yaml
We could use this for the JX pipelines, instead of running the hack/linter.sh script, which can now be used for local development.
=> feat: add a lint step for go pr task

packs/javascript-ui-nginx/charts/values.yaml
The image used in the dockerfile is nginx:alpine-stable, which has nginx configured to listen on port 80, thus I have changed internalPort to 80.
=> fix: Update internalPort to match nginx config

tasks/build-scan-push/build-scan-push.yaml
fixes https://github.com/jenkins-x/jx-docs/issues/3479
fixes https://github.com/jenkins-x/jx3-pipeline-catalog/issues/929
=> feat: setup build scan push with trivy

packs/javascript/Dockerfile, packs/typescript/Dockerfile, tasks/javascript-ui-nginx/pullrequest.yaml, tasks/javascript-ui-nginx/release.yaml, tasks/javascript/pullrequest.yaml, tasks/javascript/release.yaml, tasks/lookml/lint.yaml, tasks/typescript/pullrequest.yaml, tasks/typescript/release.yaml
NodeJS v12 Security Support ends 4/30/2022
@see https://endoflife.date/nodejs
Resolves: #1021
Signed-off-by: Hays Clark <hays.clark@gmail.com>
=> chore(nodejs): use v14 per v12 EOL

tasks/go-plugin/release.yaml
At least for jx-gitops goreleaser frequently times out, so an increase seems reasonable
=> fix: increase time out for goreleaser

tasks/go-cli/pullrequest.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
From go release notes:
```
go1.18.6 (released 2022-09-06) includes security fixes to the net/http package, as well as bug fixes to the compiler, the go command, the pprof command, the runtime, and the crypto/tls, encoding/xml, and net packages
```
=> fix: upgrade go to the latest go1.18 minor version

packs/javascript/.lighthouse/jenkins-x/release.yaml
currently the javascript pack does not work : the release pipeline pod remains pending with a message stating that the CPU is not available in the cluster.
```
k get pods
NAME                                                              READY   STATUS      RESTARTS   AGE
myrepo-node-lab3-main-release-7cs56-from-build-pack-m6-bn42f   0/10    Pending     0          40m
...
---
k describe pod myrepo-node-lab3-main-release-7cs56-from-build-pack-m6-bn42f
...
Warning  FailedScheduling   56s (x12 over 9m45s)    default-scheduler   0/3 nodes are available: 3 Insufficient cpu
```
I have tested my fix proposal that works well, and consistent with the PR https://github.com/jenkins-x/jx3-pipeline-catalog/pull/984 and the associated note in Jenkins-x blog site : …
=> Javascript pack fix pr 984

packs/lookml/.lighthouse/jenkins-x/lint.yaml, tasks/lookml/lint.yaml
today, our lookml lint pipeline that uses a custom pvc workspace started erroring out during the `git-merge` step with
```
fatal: detected dubious ownership in repository at '/workspace/source'
```
i believe it's due to the interaction between 
- the git clone step creating a `/workspace/source` directory https://github.com/jenkins-x/jx3-pipeline-catalog/blob/0c8876f333fa7f392be199ad72749a985ed02e84/tasks/git-clone/git-clone-pr.yaml#L33
- the hardcoded working dir https://github.com/jenkins-x/jx3-pipeline-catalog/blob/0c8876f333fa7f392be199ad72749a985ed02e84/tasks/git-clone/git-clone-pr.yaml#L39
- and the default tekton workspace mount behavior
> If a mountPath is not provided the workspace will be placed by default at /workspace/<name> where <name> is the workspace’s unique name.
ex: 
i …
=> fix: configure workspace mountPath to avoid permissions issues

tasks/build-scan-push/build-scan-push.yaml
This PR adds the functionality to configure the regexp used to detect vulnerabilities, so the user can choose which sensitivity.
It also includes a couple of fixes:
* don't try to update pr if not in pr pipeline
* don't output as a side effect of filtering for vulnerabilities
* make auth with ecr work
* upgrade trivy
=> feat: make build scan configurable

packs/go-cli/.lighthouse/jenkins-x/release.yaml
running `jx pipeline lint` against the packs folder results in this message
```
packs/go-cli/.lighthouse/jenkins-x/release.yaml                     failed to unmarshal YAML file packs/go-cli/.lighthouse/jenkins-x/release.yaml: failed to inherit steps: failed to process uses steps: failed to resolve git URI jenkins-x/jx3-pipeline-catalog/tasks/go-cli/release.yaml@versionStream for step build-make-build: failed to : source URI jenkins-x/jx3-pipeline-catalog/tasks/go-cli/release.yaml@versionStream task from-build-pack has no step named build-make-build
```
the `build-make-build` step in the go-cli release pipeline appears to have been renamed to `upload-binaries` in https://github.com/jenkins-x/jx3-pipeline-catalog/pull/762/files, but the pack was never updated. @rawlingsj am i reading the …
=> fix(go-cli): missing build-make-build step in release

packs/javascript-yarn/.lighthouse/jenkins-x/pullrequest.yaml, packs/javascript-yarn/.lighthouse/jenkins-x/release.yaml, packs/javascript-yarn/.lighthouse/jenkins-x/triggers.yaml, packs/javascript-yarn/Dockerfile, packs/javascript-yarn/charts/.helmignore, packs/javascript-yarn/charts/Chart.yaml, packs/javascript-yarn/charts/Kptfile, packs/javascript-yarn/charts/Makefile, packs/javascript-yarn/charts/README.md, packs/javascript-yarn/charts/templates/NOTES.txt, packs/javascript-yarn/charts/templates/_helpers.tpl, packs/javascript-yarn/charts/templates/canary.yaml, packs/javascript-yarn/charts/templates/deployment.yaml, packs/javascript-yarn/charts/templates/hpa.yaml, packs/javascript-yarn/charts/templates/ingress.yaml, packs/javascript-yarn/charts/templates/ksvc.yaml, packs/javascript-yarn/charts/templates/sa.yaml, packs/javascript-yarn/charts/templates/service.yaml, packs/javascript-yarn/charts/values.yaml, packs/javascript-yarn/preview/Kptfile, packs/javascript-yarn/preview/helmfile.yaml, packs/javascript-yarn/preview/values.yaml.gotmpl, tasks/git-clone/git-clone-pr.yaml, tasks/git-clone/git-clone.yaml, tasks/javascript-yarn/pullrequest.yaml, tasks/javascript-yarn/release.yaml
I have created a javascript-yarn pack and tasks based on the standard javascript task/pack so i can use the yarn command to build a react project, instead of npm.
In order to keep the proposed change as close to the current standard JS pack/task, i only update the command on the tasks (PR and Release), and the reference to the task on the pack PR and release files.
io did not update any version for NodeJS or the icon on the Chart template (again, to be as close to the current javascript pack/task.
I'm currently using the task from a forked repo, so they work on my deployment
=> Add Javascript-yarn task and pack

tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/release.yaml
In plugin pipelines we see error messages like:
/tekton/scripts/script-3-qzmt6: 2: source: not found 
This is due to the fact that source doesn't (necessarily) exist in sh
The only real effect I have seen though is that version, branch and such details isn't set correctly in plugins. Though this is often also due to the wrong file being specified to put the version...
=> fix: source not found in sh

packs/appserver/.lighthouse/jenkins-x/release.yaml, packs/maven-java11/.lighthouse/jenkins-x/release.yaml, packs/maven-java14/.lighthouse/jenkins-x/release.yaml, packs/maven-java16/.lighthouse/jenkins-x/release.yaml, packs/maven-java17/.lighthouse/jenkins-x/release.yaml, packs/maven-node-ruby/.lighthouse/jenkins-x/release.yaml, packs/maven-quarkus-native/.lighthouse/jenkins-x/release.yaml, packs/maven-quarkus/.lighthouse/jenkins-x/release.yaml, packs/maven/.lighthouse/jenkins-x/release.yaml, tasks/appserver/release.yaml, tasks/maven-java11/release.yaml, tasks/maven-java14/release.yaml, tasks/maven-java16/release.yaml, tasks/maven-java17/release.yaml, tasks/maven-node-ruby/release.yaml, tasks/maven-quarkus-native/release.yaml, tasks/maven-quarkus/release.yaml, tasks/maven/release.yaml
Applications typically don't need to be deployed (i.e. have their artifact uploaded to a nexus or such). So I add new step build-mvn-install for most maven based tasks and replace build-mvn-deploy with it in the packs.
Also removing clean, since it's not needed when building in a fresh clone.
The build-mvn-deploy steps are left both so existing pipelines doesn't break and to support pipelines for libraries
=> fix: don't do unnecessary deploy

tasks/go-cli/pullrequest.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
Go `build-make-build` doesn't set the correct version as $VERSION isn't set so it's just pulling from the git tags (ends up with "1.0.0-dev...").
Sourcing version from variables gives the build the correct version for the release.
=> fix: source variables in make-build to get version

tasks/git-clone/git-clone-env-pr.yaml
Adding option `-r` to `jx gitops git merge` command to avoid unexpected conflicts (e.g. `rename/rename`) when trying to rebase commits sharing the same base commit. Preserving the merge commits thus ensures commits are always applied on top of their original base branch before being merged back into the rebased branch.
This should also prevent the need for the rollback/retry logic since a regeneration commit should no longer cause any unexpected conflicts when rebasing.
=> fix: PR rebase conflicts

tasks/git-clone/git-clone-env-pr.yaml
This PR adds back the mistakenly removed [retry logic](https://github.com/brandong954/jx3-pipeline-catalog/commit/eb1c3fbf622729d0f7a23ebceeff0a7d203a7f63) within #1470 since e previous rebase attempt can change the initial state of the PR's branch, and thus cause the `regeneration` commit to see conflicts when picked in a successive rebase attempt. Note, this fix is exclusive to itself and not related to the recent [fix](https://github.com/jenkins-x/jx3-pipeline-catalog/pull/1470) for ensuring all `regeneration` commits **outside** of the PR's branch are rebased without conflict.
In other words, the `-r` flag fixed rebase conflicts for `regeneration` commits **outside** of the PR’s branch, but not within it, so both pieces are needed to hopefully resolve all the rebase issues.
=> Reset and retry rebase upon PR regeneration conflicts

helm/charts/templates/ingress.yaml, packs/C++/charts/templates/ingress.yaml, packs/D/charts/templates/ingress.yaml, packs/appserver/charts/templates/ingress.yaml, packs/csharp/charts/templates/ingress.yaml, packs/cwp/charts/templates/ingress.yaml, packs/go-mongodb/charts/templates/ingress.yaml, packs/go/charts/templates/ingress.yaml, packs/gradle/charts/templates/ingress.yaml, packs/javascript-ui-nginx/charts/templates/ingress.yaml, packs/javascript/charts/templates/ingress.yaml, packs/maven-java11/charts/templates/ingress.yaml, packs/maven-java14/charts/templates/ingress.yaml, packs/maven-java16/charts/templates/ingress.yaml, packs/maven-java17/charts/templates/ingress.yaml, packs/maven-node-ruby/charts/templates/ingress.yaml, packs/maven-quarkus-native/charts/templates/ingress.yaml, packs/maven-quarkus/charts/templates/ingress.yaml, packs/maven/charts/templates/ingress.yaml, packs/ml-python-gpu-service/charts/templates/ingress.yaml, packs/ml-python-gpu-training/charts/templates/ingress.yaml, packs/ml-python-service/charts/templates/ingress.yaml, packs/ml-python-training/charts/templates/ingress.yaml, packs/php/charts/templates/ingress.yaml, packs/python/charts/templates/ingress.yaml, packs/ruby/charts/templates/ingress.yaml, packs/rust/charts/templates/ingress.yaml, packs/scala/charts/templates/ingress.yaml, packs/typescript/charts/templates/ingress.yaml
It's a bit surprising that setting labels on ingresses via the helm charts of applications created from the packs has been broken until now. But so it is...
=> fix: add missing labels field

tasks/javascript-yarn/pullrequest.yaml
Update Node docker image to v21.
version 14 has high severity security issues reported on the official repo.
=> Update pullrequest.yaml - update version of node to v21

tasks/go-cli/pullrequest.yaml, tasks/go-cli/release.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
=> chore: upgrade go to 1.22.3

tasks/git-clone/git-clone-env-pr-partial.yaml
Pipelines using the default set of `git-clone` tasks can experience slowdown as the repo's git history grows, as these tasks use the default `git clone` command, getting all branches, files and commits.
This PR creates a new task definition (`tasks/git-clone/git-clone-env-pr-partial.yaml`) and generates a [treeless git clone](https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone) of the target repo, using `git clone --filter=tree:0 --no-checkout`. This downloads all reachable commits, while preserving git history. trees and blobs can be downloaded on-demand.
This can provide significant speed improvements for single-use build pipelines, especially for repositories with long histories.
Other suggested solutions such as shallow clones (raised here …
=> feat: add git-clone task for partial cloning

tasks/go-cli/pullrequest.yaml, tasks/go-cli/release.yaml, tasks/go-mongodb/pullrequest.yaml, tasks/go-mongodb/release.yaml, tasks/go-plugin-multiarch/pullrequest.yaml, tasks/go-plugin-multiarch/release.yaml, tasks/go-plugin/pullrequest.yaml, tasks/go-plugin/release.yaml, tasks/go/pullrequest.yaml, tasks/go/release.yaml
related to https://github.com/jenkins-x/lighthouse/pull/1650
=> chore(golang): avoid error tektoncd/pipeline@v1.1.0 requires go >= 1.24.0

tasks/git-clone/git-clone-env-pr-partial.yaml, tasks/git-clone/git-clone-env-pr.yaml, tasks/git-clone/git-clone-pr.yaml, tasks/git-clone/git-clone.yaml
Tekton v1 is automatically doing the equivalent of `git config --global credential.helper store`, so that isn't needed. Tekton is also reinitializing ~/.gitconfig before each step, so storing user.name and user.email there doesn't work.
=> fix: tekton is overwriting ~/.gitconfig
